---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - puppeteers_prometheus_prometheus_misc_manage_firewalld is boolean
      - puppeteers_prometheus_prometheus_misc_firewalld_zone is string
      - puppeteers_prometheus_prometheus_misc_port is number
      - puppeteers_prometheus_prometheus_misc_extra_alert_rules is string

- name: Add additional alert rules
  ansible.builtin.copy:
    content: "{{ puppeteers_prometheus_prometheus_misc_extra_alert_rules }}"
    dest: /etc/prometheus/rules/prometheus_misc_extra.rules
    owner: root
    group: prometheus
    mode: '0640'
  notify: reload prometheus

- name: Open port in firewalld
  ansible.posix.firewalld:
    zone: "{{ puppeteers_prometheus_prometheus_misc_firewalld_zone }}"
    port: "{{ puppeteers_prometheus_prometheus_misc_port }}/tcp"
    state: enabled
    immediate: true
    permanent: true
  when: puppeteers_prometheus_prometheus_misc_manage_firewalld
