---
puppeteers_prometheus_updates_exporter_manage_firewalld: false
puppeteers_prometheus_updates_exporter_firewalld_zone: public
puppeteers_prometheus_updates_exporter_port: 9101
puppeteers_prometheus_updates_exporter_interval_seconds: 3600
puppeteers_prometheus_updates_exporter_log_level: "info"
puppeteers_prometheus_updates_exporter_release_version: "0.1.3"
puppeteers_prometheus_updates_exporter_manage_config: true
puppeteers_prometheus_updates_exporter_base_url: "https://github.com/Puppet-Finland/updates-exporter/releases/download/v{{ puppeteers_prometheus_updates_exporter_release_version}}/updates_exporter_{{ puppeteers_prometheus_updates_exporter_release_version }}_linux_amd64"
