---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - puppeteers_prometheus_alertmanager_misc_manage_firewalld is boolean
      - puppeteers_prometheus_alertmanager_misc_firewalld_zone is string
      - puppeteers_prometheus_alertmanager_misc_port is number

- name: Open port in firewalld
  ansible.posix.firewalld:
    zone: "{{ puppeteers_prometheus_alertmanager_misc_firewalld_zone }}"
    port: "{{ puppeteers_prometheus_alertmanager_misc_port }}/tcp"
    state: enabled
    immediate: true
    permanent: true
  when: puppeteers_prometheus_alertmanager_misc_manage_firewalld

- name: Write SSL Certificates
  ansible.builtin.include_role:
    name: puppeteers.prometheus._ssl_certs
  vars:
    puppeteers_prometheus__ssl_certs_dir: "{{ puppeteers_prometheus_alertmanager_misc_ssl_dir }}"
    puppeteers_prometheus__ssl_certs_owner: "alertmanager"
    puppeteers_prometheus__ssl_certs_key: "{{ puppeteers_prometheus_alertmanager_misc_ssl_key }}"
    puppeteers_prometheus__ssl_certs_certificate: "{{ puppeteers_prometheus_alertmanager_misc_ssl_certificate }}"
  when:
    - puppeteers_prometheus_alertmanager_misc_ssl_key is defined
    - puppeteers_prometheus_alertmanager_misc_ssl_certificate is defined
