---
- name: puppeteers.prometheus.node_exporter | validate parameters
  ansible.builtin.assert:
    that:
      - node_exporter_firewalld_zone is string

- name: puppeteers.prometheus.node_exporter | install package
  ansible.builtin.package:
    name: prometheus-node-exporter
    state: present
  notify: puppeteers.prometheus.node_exporter | restart service

- name: puppeteers.prometheus.node_exporter | create textfile collector directory
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    owner: node-exporter
    group: node-exporter
    mode: '0755'

- name: puppeteers.prometheus.node_exporter | create systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/node_exporter.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: puppeteers.prometheus.node_exporter | configure node exporter
  ansible.builtin.template:
    src: templates/01_ansible.conf.j2
    dest: /etc/systemd/system/node_exporter.service.d/01_ansible.conf
    owner: root
    group: root
    mode: '0640'
  notify:
    - systemctl daemon-reload
    - puppeteers.prometheus.node_exporter | restart service

- name: puppeteers.prometheus.node_exporter | enable service
  ansible.builtin.service:
    name: node_exporter
    enabled: true
    state: started

- name: puppeteers.prometheus.node_exporter | open hole in firewall
  ansible.builtin.firewalld:
    zone: "{{ node_exporter_firewalld_zone }}"
    service: prometheus-node-exporter
    state: enabled
    immediate: true
    permanent: true
